#ifndef _BEACHJUDGE_CONFIG_H_
#define _BEACHJUDGE_CONFIG_H_

//- Version -
#define BEACHJUDGE_VERSION_MAJOR 0
#define BEACHJUDGE_VERSION_MINOR 01

//- Threading -
#define BEACHJUDGE_USEPOSIXTHREAD 1
#define BEACHJUDGE_USEWINTHREAD 0

//- Networking -
#define BEACHJUDGE_USEPOSIXSOCKET 1
#define BEACHJUDGE_USEWINSOCKET 0

#endif
