macro(fetch_rethinkdb)

set(T "RETHINKDB")
if(NOT RETHINKDB_FOUND)
	set(T___NAME "${T_${T}_NAME}")
	set(T___PATH ${T_${T}_PATH})
	set(T___DL_FILE ${BUILD_EXT_DIR}/${T_${T}_DL_FILE})
	set(T___DL_FOLDER ${BUILD_EXT_DIR}/${T_${T}_DL_FOLDER})
	set(T___DL_MD5 ${T_${T}_DL_MD5})
	set(T___DL_URI ${T_${T}_DL_URI})
	set(T___CK_FILE ${T___PATH}/${T_${T}_CK_FILE})

	if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")

		if(NOT EXISTS ${T___CK_FILE})
			if(NOT EXISTS ${T___DL_FILE})
				message("Downloading ${T___NAME} <${T___DL_URI}>...")
				file(DOWNLOAD ${T___DL_URI} ${T___DL_FILE} STATUS T___STATUS SHOW_PROGRESS EXPECTED_MD5 ${T___DL_MD5})
				list(GET T___STATUS 0 T___STATUS)
				if(T___STATUS)
					file(REMOVE ${T___DL_FILE})
					return()
				endif()
			endif()
			message("Unzipping ${T___NAME}...")
			file(MAKE_DIRECTORY ${T___PATH})
			do_unzip(${T___DL_FILE} ${T___PATH})
		endif()

		set(RETHINKDB_FOUND 1 CACHE INTERNAL "")
	endif()

	if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
		set(T___CK_BIN ${T___PATH}/${T_${T}_CK_BIN})
		if(NOT EXISTS ${T___CK_FILE})
			if(NOT EXISTS ${T___DL_FILE})
				message("Downloading ${T___NAME} <${T___DL_URI}>...")
				file(DOWNLOAD ${T___DL_URI} ${T___DL_FILE} STATUS T___STATUS SHOW_PROGRESS EXPECTED_MD5 ${T___DL_MD5})
				list(GET T___STATUS 0 T___STATUS)
				if(T___STATUS)
					file(REMOVE ${T___DL_FILE})
					return()
				endif()
			endif()

			execute_process(COMMAND tar xf ${T___DL_FILE} WORKING_DIRECTORY ${BUILD_EXT_DIR})
			execute_process(COMMAND cmake -E rename ${T___DL_FOLDER} ${T___PATH} WORKING_DIRECTORY ${BUILD_EXT_DIR})
		endif()

		if(NOT EXISTS ${T___CK_BIN})
			execute_process(COMMAND ./configure --allow-fetch WORKING_DIRECTORY ${T___PATH})
			execute_process(COMMAND make WORKING_DIRECTORY ${T___PATH})
		endif()

		set(RETHINKDB_FOUND 1 CACHE INTERNAL "")
		set(RETHINKDB ${T___PATH}/build/release/rethinkdb CACHE INTERNAL "")
	endif()
endif()

endmacro()
