# LIBWEBSOCKETS_INCLUDE_DIR
# LIBWEBSOCKETS_LIBRARY_DIR
# LIBWEBSOCKETS_LIBRARIES
# LIBWEBSOCKETS_FOUND

find_path(LIBWEBSOCKETS_INCLUDE_DIR libwebsockets.h
	PATH_SUFFIXES lib
)

find_library(LIBWEBSOCKETS_LIBRARIES websockets
	PATH_SUFFIXES lib
)

get_filename_component(LIBWEBSOCKETS_LIBRARY_DIR
	${LIBWEBSOCKETS_LIBRARIES} PATH)

set(LIBWEBSOCKETS_FOUND "NO")
if(LIBWEBSOCKETS_INCLUDE_DIR)
	if(LIBWEBSOCKETS_LIBRARIES)
		set(LIBWEBSOCKETS_FOUND "YES")
	endif()
endif()

mark_as_advanced(
	LIBWEBSOCKETS_LIBRARY_DIR
	LIBWEBSOCKETS_INCLUDE_DIR
	LIBWEBSOCKETS_LIBRARIES
)
