# NodeJS
set(T "NODEJS")
set(T_${T}_PATH "${BUILD_EXT_DIR}/nodejs")
if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	set(T_${T}_DL_FILE "node.exe")
	set(T_${T}_DL_MD5 "4376fac6561bb9df463cef14d913b1d2")
	set(T_${T}_DL_URI "https://nodejs.org/dist/v6.4.0/win-x64/node.exe")
	set(T_${T}_CK_FILE "bin/node.exe")
endif()
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
	set(T_${T}_DL_FILE "node-v6.4.0-linux-x64.tar.xz")
	set(T_${T}_DL_FOLDER "node-v6.4.0-linux-x64")
	set(T_${T}_DL_MD5 "3c7157b017c279135325d19d650caa9d")
	set(T_${T}_DL_URI "https://nodejs.org/dist/v6.4.0/node-v6.4.0-linux-x64.tar.xz")
	set(T_${T}_CK_FILE "bin/node")
endif()

# RethinkDB
set(T "RETHINKDB")
set(T_${T}_PATH "${BUILD_EXT_DIR}/rethinkdb")
if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
	set(T_${T}_DL_FILE "rethinkdb.zip")
	set(T_${T}_DL_MD5 "8cc0021e858ee92390865f281c3b8ba6")
	set(T_${T}_DL_URI "https://download.rethinkdb.com/windows/rethinkdb-2.3.4.zip")
	set(T_${T}_CK_FILE "rethinkdb.exe")
endif()
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
	set(T_${T}_DL_FILE "rethinkdb-2.3.4.tgz")
	set(T_${T}_DL_FOLDER "rethinkdb-2.3.4")
	set(T_${T}_DL_MD5 "cf81117ed3acdf28cea1d62ef45f3340")
	set(T_${T}_DL_URI "https://download.rethinkdb.com/dist/rethinkdb-2.3.4.tgz")
	set(T_${T}_CK_FILE "Makefile")
	set(T_${T}_CK_BIN "build/release/rethinkdb")
endif()

# Python2
set(T "PYTHON2")
set(T_${T}_NAME "python2")
set(T_${T}_PATH "${BUILD_EXT_DIR}/python2")
set(T_${T}_DL_FILE "python-2.7.11.amd64.msi")
set(T_${T}_DL_FOLDER "python-2.7.11.amd64.msi")
set(T_${T}_DL_MD5 "25acca42662d4b02682eee0df3f3446d")
set(T_${T}_DL_URI "https://www.python.org/ftp/python/2.7.11/python-2.7.11.amd64.msi")
set(T_${T}_CK_FILE "python.exe")